"""empty message

Revision ID: 37eabcbbb8fb
Revises: 1c62104cd9f7
Create Date: 2019-10-17 21:00:22.815191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37eabcbbb8fb'
down_revision = '1c62104cd9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('df_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.String(length=20), nullable=False),
    sa.Column('addr', sa.String(length=256), nullable=False),
    sa.Column('zip_code', sa.String(length=6), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('df_address')
    # ### end Alembic commands ###
