"""empty message

Revision ID: 5271c261ad4e
Revises: 71a0d244b6ce
Create Date: 2019-10-22 20:45:06.857945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5271c261ad4e'
down_revision = '71a0d244b6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('df_order_info', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('df_order_info', 'create_time')
    # ### end Alembic commands ###
