"""empty message

Revision ID: 6464d6f2bbcb
Revises: f025f89b250b
Create Date: 2019-10-19 18:25:20.006645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6464d6f2bbcb'
down_revision = 'f025f89b250b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('df_index_promotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('index', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('df_index_banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('index', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['df_goods_sku.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('df_index_type_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('sku', sa.Integer(), nullable=True),
    sa.Column('display_type', sa.SmallInteger(), nullable=True),
    sa.Column('index', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['df_goods_sku.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type'], ['df_goods_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('df_goods_image_ibfk_1', 'df_goods_image', type_='foreignkey')
    op.create_foreign_key(None, 'df_goods_image', 'df_goods_sku', ['sku'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'df_goods_image', type_='foreignkey')
    op.create_foreign_key('df_goods_image_ibfk_1', 'df_goods_image', 'df_goods_sku', ['sku'], ['id'])
    op.drop_table('df_index_type_goods')
    op.drop_table('df_index_banner')
    op.drop_table('df_index_promotion')
    # ### end Alembic commands ###
